// ─── AI Design System Manifest — Type Definitions ──────────────────────────

export type ComponentDomain = 'ui' | 'travel';
export type PropType =
  | 'string'
  | 'boolean'
  | 'number'
  | 'enum'
  | 'React.ReactNode'
  | 'React.CSSProperties'
  | 'function'
  | 'object'
  | 'array'
  | 'ref';

// ─── Token types ─────────────────────────────────────────────────────────────

export interface DesignToken {
  /** CSS custom property name, e.g. --color-primary-default */
  name: string;
  /** Raw CSS value */
  value: string;
  /** Top-level category: color | spacing | typography | motion | shadow | shape | breakpoint */
  category: string;
  /** Sub-category, e.g. primary, background, foreground */
  group?: string;
  /** Human-readable description */
  description?: string;
}

export interface TokenManifest {
  /** Total token count */
  total: number;
  /** Tokens by category */
  byCategory: Record<string, DesignToken[]>;
  /** Flat list of all tokens */
  all: DesignToken[];
}

// ─── Component types ─────────────────────────────────────────────────────────

export interface PropDef {
  name: string;
  type: PropType;
  /** Enum values if type === 'enum' */
  values?: string[];
  required: boolean;
  default?: string;
  description?: string;
}

export interface VariantAxis {
  /** CVA variant prop name, e.g. variant, size */
  name: string;
  /** All possible values */
  values: string[];
  /** Default value if defined */
  default?: string;
}

export interface SlotDef {
  /** Prop name that accepts slot content, e.g. icon, prefix, children */
  name: string;
  description?: string;
}

export interface ComponentEntry {
  /** Stable identifier, e.g. ui/button, travel/flight-card */
  id: string;
  /** PascalCase export name */
  name: string;
  domain: ComponentDomain;
  /** Relative path from packages/ui/src/components/ */
  path: string;
  /** Import specifier consumers should use */
  importFrom: string;
  /** All exported names from the barrel index */
  exports: string[];
  /** Props interface entries */
  props: PropDef[];
  /** CVA variant axes */
  variants: VariantAxis[];
  /** Named slot props */
  slots: SlotDef[];
  /** Radix primitive this wraps, if any */
  radixPrimitive?: string;
  /** @uiComponent JSDoc tag description */
  description?: string;
  /** @pattern JSDoc tags */
  patterns?: string[];
  /** @uses JSDoc tags — other component IDs this depends on */
  uses?: string[];
  /** CSS class names generated by this component */
  cssClasses: string[];
  /** Whether the component has a .css contract file */
  hasCssContract: boolean;
  /** Whether the component accepts className */
  acceptsClassName: boolean;
  /** When/why to use this component — AI selection guidance */
  aiHints?: {
    whenToUse: string;
    whenNotToUse?: string;
    alternatives?: string[];
    preferOver?: string;
    neverUseFor?: string;
  };
  /** Interaction model — states, interactions, animations */
  behavior?: {
    states: string[];
    interactions: string[];
    animations?: string[];
    responsive?: string;
  };
  /** Accessibility contract — role, keyboard, ARIA, WCAG */
  accessibility?: {
    role: string;
    keyboardNav: string;
    ariaAttributes?: string[];
    wcag?: string[];
    screenReader?: string;
  };
  /** Canonical JSX usage examples */
  examples?: Array<{ label: string; code: string }>;
}

// ─── Dependency graph ─────────────────────────────────────────────────────────

export interface DependencyEdge {
  from: string;
  to: string;
  /** Type of import relationship */
  kind: 'component' | 'util' | 'token' | 'external';
}

export interface DependencyGraph {
  nodes: string[];
  edges: DependencyEdge[];
  /** Adjacency list: component id → direct component dependencies */
  adjacency: Record<string, string[]>;
}

// ─── Pattern detection ────────────────────────────────────────────────────────

export interface UIPattern {
  /** Pattern identifier, e.g. search-form, booking-flow */
  id: string;
  /** Human-readable label */
  label: string;
  description: string;
  /** Component IDs that typically compose this pattern */
  components: string[];
  /** Example JSX snippet in DSL form */
  example?: string;
}

export interface ScreenMapping {
  /** Screen/page identifier, e.g. flights-search, hotel-listing */
  id: string;
  label: string;
  /** Component IDs present on this screen */
  components: string[];
  /** Pattern IDs present on this screen */
  patterns: string[];
  /** File path hint */
  filePath?: string;
}

// ─── Manifest ─────────────────────────────────────────────────────────────────

export interface ManifestMeta {
  generatedAt: string;
  version: string;
  componentCount: number;
  tokenCount: number;
  patternCount: number;
}

export interface UIManifest {
  meta: ManifestMeta;
  tokens: TokenManifest;
  components: ComponentEntry[];
  dependencyGraph: DependencyGraph;
  patterns: UIPattern[];
  screenMappings: ScreenMapping[];
  /** Compact DSL string for ultra-low token usage */
  dsl: string;
}
